numpy 数据类型 
bool  : false true
int_  : (long int32 ,int64)
intc : int32 int64
intp : 索引的整数类型 （c size_t）
int8 : -128 to 127
int16 : -2^15-1  to 2^15-1
int32 : -2^32-1 to 2^32-1
int64: 
unit8: 无符号整数 [0,2^8-1]
unit16: [0,2^16-1]
unit32
unit64
float_ : float64
float16 : 半精度浮点数 ： 符号位1个，指数为5个，尾数10个
float32 : 单精度浮点数 ： 符号位1 个，指数位8个，尾数23个
float64:  双精度浮点数 ： 符号位1个，指数位11个，尾数53个
complex_ : complex128 : 128 位复数
complex64 ： 双32位浮点数 （实数+ 虚数）
complex128 : 双64位浮点数

In [2]:
import numpy as np
# 全局导包

In [6]:
# 创建一维不同类型数组
array_list = [0,1,2,3,4,5,6,7,8]
# int 
array_np = np.array(array_list)
print(array_np,type(array_np))
#float
array_np = np.array(array_list,float)
print(array_np,type(array_np))
# boolean
array_np = np.array(array_list,bool)
print(array_np,type(array_np))
# complex
array_np = np.array(array_np,complex)
print(array_np,type(array_np))

[0 1 2 3 4 5 6 7 8] <class 'numpy.ndarray'>
[0. 1. 2. 3. 4. 5. 6. 7. 8.] <class 'numpy.ndarray'>
[False  True  True  True  True  True  True  True  True] <class 'numpy.ndarray'>
[0.+0.j 1.+0.j 1.+0.j 1.+0.j 1.+0.j 1.+0.j 1.+0.j 1.+0.j 1.+0.j] <class 'numpy.ndarray'>


In [9]:
# 二维数组 [(),(),()]
# n 维 数组  
array_row1 = (1,2,3)
array_row2 = (4,7,8)
array_row3 = (9,100,88)
array_row3_col3= np.array([array_row1,array_row2,array_row3])
print(array_row3_col3)
# m.n 维数组
array_row1 = (1,2,3)
array_row2 = (4,7,8)
array_row3 = (9,100,88)
array_row4 = (9,100,111)
array_row4_col3= np.array([array_row1,array_row2,array_row3,array_row4],float)
print(array_row4_col3)
# 多维数组

[[  1   2   3]
 [  4   7   8]
 [  9 100  88]]
[[  1.   2.   3.]
 [  4.   7.   8.]
 [  9. 100.  88.]
 [  9. 100. 111.]]


In [15]:
#特殊矩阵
# 0 矩阵
zero_matrix = np.zeros(shape=(2,3),dtype=float)
print(zero_matrix.shape)
print(zero_matrix)
# 1 矩阵
one_matrix = np.ones(shape=(3,3),dtype=complex)
print(one_matrix.shape)
print(one_matrix)
# arange  等差数组
ap_array = np.arange(1,5,0.5)
print(ap_array)
print(type(ap_array))
# 单位矩阵
identity_matrix = np.eye(4,dtype=int)
print(identity_matrix)
# 默认 float
identity_matrix = np.eye(4)
print(identity_matrix)

# random [0,1） 
# 平均分布数组
array_np = np.random.random(8)
print(array_np)
# 随机范围整数
array_np = np.random.randint(1,10,10)
print(array_np)
# 正态分布的随机数组  均值mu  标准差sigma
mu,sigma = 1,0.1
array_normal = np.random.normal(mu,sigma,5)
print(array_normal)

(2, 3)
[[0. 0. 0.]
 [0. 0. 0.]]
(3, 3)
[[1.+0.j 1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j 1.+0.j]]
[1.  1.5 2.  2.5 3.  3.5 4.  4.5]
<class 'numpy.ndarray'>
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[0.64389997 0.38295693 0.73893085 0.53682321 0.7130833  0.43117375
 0.88361883 0.20383966]
[5 8 7 7 6 8 9 8 2 4]
[1.07630106 1.15778379 0.79265161 0.95871532 1.10824455]


In [22]:
# numpy 数组访问
# 生成式
array_np = np.array([(1,2,3),(4,5,6),(9,10,12)])
print(array_np)
print(array_np[0])
# 剩余矩阵  切片？
print(array_np[1:]) 
print(array_np[1:].shape)
# 先行后列
print(array_np[:,:1])
print(array_np[:2,:1])
# 固定数值
print(array_np[2][1])


[[ 1  2  3]
 [ 4  5  6]
 [ 9 10 12]]
[1 2 3]
[[ 4  5  6]
 [ 9 10 12]]
(2, 3)
[[1]
 [4]
 [9]]
[[1]
 [4]]
10


In [ ]:
# 数组遍历
# 一唯数组  
# array_one = np.array([1,2,3,4,5,6])
array_one = np.arange(1,7,1)
for row in array_one:
    print(row)
# 二维数组
array_two = np.array([[1,2],[2,3],[4,5]])
print(array_two)
for row_num1,row_num2 in array_two:
    print(row_num1,row_num2)
# 三维数组
array_three = np.array([(1,2,3),(4,5,6),(7,8,9)])
print(array_three)
# unpack  解包对应（1,2,3） 个数
# for row_num1,row_num2 in array_three:
#     print(row_num1,row_num2)
for row_num1,row_num2,row_num3 in array_three:
    print(row_num1,row_num2,row_num3)
# 多维解包不方便

1
2
3
4
5
6
[[1 2]
 [2 3]
 [4 5]]
1 2
2 3
4 5
[[1 2 3]
 [4 5 6]
 [7 8 9]]
1 2 3
4 5 6
7 8 9


In [ ]:
# numpy 数组的属性
row_num = np.random.randint(1,99,10)
print(row_num,type(row_num))
row_num = tuple(row_num)
print(row_num,type(row_num))
array_matrix = np.array([tuple(np.random.randint(1,99,10)) for i in range(3)])
print(array_matrix)
# ndim 秩   数组的维度 (dimension)（数组轴的个数） rank
print("ndim",array_matrix.ndim)
# shape  行数 列数
print("shape",array_matrix.shape)
# size  数组元素总个数   rows*cols
print("size",array_matrix.size)
# dtype  数组中的元素类型的对象
print("dtype",array_matrix.dtype)

[70 27 23 75  7 93 75 41 51 93] <class 'numpy.ndarray'>
(70, 27, 23, 75, 7, 93, 75, 41, 51, 93) <class 'tuple'>
[[37 67 14 95 88 15 94 21  4 64]
 [26 95 31 85 22 47 20 38 19  1]
 [39 78 26 58 17 33 18 11 86 64]]
ndim 2
shape (3, 10)
size 30
dtype int32


In [50]:
# numpy 数组操作
array_matrix = np.array([(1,2),(3,4)])
# 数值存在  in  维度越大 耗时越大
print(3 in array_matrix)
# reshape 数组重排列  个数保持不变
zero_array = np.zeros(shape=(3,3,3))
print(zero_array)
print(zero_array.size)
# reshape 暂时存在
zero_array.reshape(zero_array.size)
# 转置 行列互换  traspose  .T
numpy_array = np.array([tuple(np.random.randint(1,10,3)) for i in range(4)])
print(numpy_array.shape)
print(numpy_array)
transpose_array = numpy_array.transpose()
print(transpose_array)
print(transpose_array.shape)
#  转置转置等于本身
print(transpose_array.T.shape)
# 线性代数 相关知识
 
# flatten  多维变成一维数组  ，每个元组长度相同
array_np = np.array([(1,2),(3,4),(5,6)])
array_flatten = array_np.flatten()
print(array_flatten.shape)
print(array_flatten)

# newaxis ： 增加维度
print("shape_before",array_np.shape)
array_newaxis = array_np[:,np.newaxis]
print("shape_after",array_newaxis.shape)
print(array_newaxis)

array_newaxis = array_np[:,:,np.newaxis]
print("shape_after",array_newaxis.shape)
print(array_newaxis)

True
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
27
(4, 3)
[[7 7 3]
 [7 9 3]
 [9 5 8]
 [2 2 4]]
[[7 7 9 2]
 [7 9 5 2]
 [3 3 8 4]]
(3, 4)
(4, 3)
(6,)
[1 2 3 4 5 6]
shape_before (3, 2)
shape_after (3, 1, 2)
[[[1 2]]

 [[3 4]]

 [[5 6]]]
shape_after (3, 2, 1)
[[[1]
  [2]]

 [[3]
  [4]]

 [[5]
  [6]]]


In [ ]:
# 数学操作
# 加减乘除  满足运算的规则
# * + - /
array_a = np.ones((2,2))
array_b = np.array([(-1,-1),(1,1)])
print(array_a)
print(array_b)
print(array_a * array_b)
print(array_a - array_b)
print(array_a + array_b)
print(array_a / array_b)
# dytype : 浮点型数据 

#  求和   sum 类似对象内部
print(array_a.sum())
print(array_b.sum())
#  求积  prod
print(array_a.prod())
print(array_b.prod())
# 平均数  方差 标准差  最大值  最小值
print("mean",array_a.mean())
print("var",array_a.var())
print("std",array_a.std())
print("max",array_a.max())
print("min",array_a.min())
# 最大值的索引值 argmax 最小值的索引值 argmin  
print("argmax",array_a.argmax())
print("argmin",array_a.argmin())
# 取元素的上限、 下限 ceil floor
print("ceil",np.ceil(array_a))
print("floor",np.floor(array_a))
# 四舍五入 rint
print("rint",np.rint(array_a))

# 排序
arrary_a = np.array([5,676,4334,232,12,45])
print(arrary_a.sort())


[[1. 1.]
 [1. 1.]]
[[-1 -1]
 [ 1  1]]
[[-1. -1.]
 [ 1.  1.]]
[[2. 2.]
 [0. 0.]]
[[0. 0.]
 [2. 2.]]
[[-1. -1.]
 [ 1.  1.]]
4.0
0
1.0
1
mean 1.0
var 0.0
std 0.0
max 1.0
min 1.0
argmax 0
argmin 0
ceil [[1. 1.]
 [1. 1.]]
floor [[1. 1.]
 [1. 1.]]
rint [[1. 1.]
 [1. 1.]]
None


In [63]:
 # abs 绝对值
array_np = np.array([(-1,-2),(-3,-4)])
array_num = np.abs(array_np)
print(array_num)
# sign 
array_num = np.sign(array_np)
print(array_num)
# sqrt, log,log10, exp, sin, cos, tan, arcsin, arccos, arctan, sinh, cosh, tanh,arcsinh, arccosh,arctanh

[[1 2]
 [3 4]]
[[-1 -1]
 [-1 -1]]


In [72]:
# 内积  dot
# 对于多维数组，它的通⽤计算公式如下，即结果数组中的每个元素都是：数组 a 的最后⼀维上的所有元素与数组 b 的倒数第⼆位上的所有元素的乘积和：
# dot(a, b)[i,j,k,m]= sum(a[i,j,:] * b[k,:,m])
import numpy as np 
array_a = np.array([[1,2],[3,4]],dtype=np.float32)
array_b = np.array([[6,7],[8,9]],dtype=np.float32)
#dot
result = np.dot(array_a,array_b)
print(result)

# @
result = array_a @ array_b
print(result)

# trace : 矩阵的迹
print(np.trace(np.ones((2,2))))
# eig  特征值  特征向量
# 只有方阵才能进行特征值分解
# e_vals,e_vecs = np.linalg.eig(a)

# inv 逆
A = np.array([[1, -2, 1], [0, 2, -1], [1, 1, -2]])
B = np.linalg.inv(A)
print("inv",B)
# 使用 linalg.det求得方阵的行列式
A_abs = np.linalg.det(A)
print("det",A_abs)
# 伴随矩阵 A*= |A| A-
A_bansui = B * A_abs
print("A_bansui",A_bansui)


# qr  QR 分解

# svd  奇异值分解

# solve ： 解线性方程 Ax=b 
a = np.array([[1, 2, 1], [2, -1, 3], [3, 1, 2]])
b = np.array([7,7,18])
# 使用 linalg.solve 方法解方程，参数a指的是系数矩阵，参数b指的是常数项矩阵
result = np.linalg.solve(a,b)
print(result)
# 结果验证
print(np.dot(a,result))
# lstsq  计算Ax=b 的最小二乘解



[[22. 25.]
 [50. 57.]]
[[22. 25.]
 [50. 57.]]
2.0
inv [[ 1.          1.          0.        ]
 [ 0.33333333  1.         -0.33333333]
 [ 0.66666667  1.         -0.66666667]]
det -3.0000000000000004
A_bansui [[-3. -3. -0.]
 [-1. -3.  1.]
 [-2. -3.  2.]]
[ 7.  1. -2.]
[ 7.  7. 18.]


In [ ]:
# numpy 广播机制
# ⼴播 (Broadcast) 是 numpy 对不同形状 (shape) 的数组进⾏数值计算的⽅式，对数组的算术运算通常在相应的元素上进⾏。如果两个数组 a 和 b 形状相同，即满⾜
# a.shape == b.shape，那么 a*b 的结果就是 a 与 b 数组对应位相乘。这要求维数相同，且各维度的⻓度相同。
# 当运算中的 2 个数组的形状不同时，numpy 将⾃动触发⼴播机制
arrary_a = np.array([(1,2),(2,3),(1,2),(2,3)])
arrary_b = np.array([-1,1])
# shape(2) -> shape(1,2) --> shape(4,2)
print(arrary_a+array_b)

[[ 8  9 19]
 [ 9  6 21]
 [10  8 20]]
